# List of devices to manage with ADB
devices:
  - id: "25281JEGR07570"
    alias: "Pixel 6a"
  - id: "192.168.50.101"
    alias: "ATV01"

# List of tasks the script can perform on the devices
tasks:
  - wikipedia_search: true
  - google_search: true  # Add this option to enable Google search

# Timing parameters to introduce randomness in the script's behavior
timing_parameters:
  min_delay_between_tasks: 3  # Minimum delay between tasks (in seconds)
  max_delay_between_tasks: 10  # Maximum delay between tasks (in seconds)

# Loading delays for Google and Wikipedia
loading_delays:
  google: 10  # Initial delay for loading Google (in seconds)
  wikipedia: 10  # Initial delay for loading Wikipedia (in seconds)

# Loop settings for task execution
loop_settings:
  min_loops: 1  # Minimum number of loops to run (0 for infinite)
  max_loops: 5  # Maximum number of loops to run
