# List of devices to manage with ADB
devices:
  - id: "25281JEGR07570"
    alias: "Pixel 6a"

# List of tasks the script can perform on the devices
tasks:
  - wikipedia_search: true
  - google_search: true  # Add this option to enable Google search

# Timing parameters to introduce randomness in the script's behavior
timing_parameters:
  min_delay_between_tasks: 3  # Minimum delay between tasks (in seconds)
  max_delay_between_tasks: 10 # Maximum delay between tasks (in seconds)

# Search queries to randomly perform on Wikipedia
search_queries:
  - "Quantum mechanics"
  - "Artificial intelligence"
  - "Machine learning"
  - "History of the internet"
  - "Python programming language"
  - "Cryptography"
  - "History of space exploration"
  - "Renaissance art"
  - "Black hole formation"
  - "Photosynthesis process"
  - "Evolution of mammals"
  - "Ancient Egyptian civilization"
  - "History of the Roman Empire"
  - "Theory of relativity"
  - "Thermodynamics"
  - "Plate tectonics"
  - "History of World War II"
  - "String theory"
  - "History of computers"
  - "Blockchain technology"
  - "History of video games"
  - "Classical music composers"
  - "Baroque architecture"
  - "Genetic engineering"
  - "Nanotechnology"
  - "Particle physics"
  - "Augmented reality"
  - "Neuroscience breakthroughs"
  - "Cybersecurity threats"
  - "History of encryption"
  - "Quantum computing"
  - "3D printing technology"
  - "History of mathematics"
  - "Dark matter"
  - "Fossil fuel impact on the environment"
  - "History of photography"
  - "Ocean ecosystems"
  - "History of human migration"
  - "Evolution of birds"
  - "History of astronomy"
  - "Meteorology and climate change"
  - "Cultural anthropology"
  - "History of the Silk Road"
  - "Fermat's last theorem"
  - "Number theory"
  - "Medieval history of Europe"
  - "Colonialism in Africa"
  - "History of medicine"
  - "DNA replication process"
  - "Types of renewable energy"
  - "The Big Bang theory"
  - "Human immune system"
  - "The Industrial Revolution"
  - "History of robotics"
  - "Astrobiology"
  - "History of aviation"
  - "History of the English language"
  - "Cognitive psychology"
  - "Philosophy of mind"
  - "Evolutionary biology"
  - "Globalization and its effects"
  - "Subatomic particles"
  - "History of feminism"
  - "Virtual reality"
  - "Greek mythology"
  - "World mythology"
  - "Saturn's rings"
  - "History of democracy"
  - "History of quantum theory"
  - "Oceanography"
  - "History of artificial intelligence"
  - "Sustainable agriculture"
  - "Human body systems"
  - "Evolution of insects"
  - "History of the internet"
  - "Mitochondrial DNA"
  - "History of blockchain"
  - "Wireless communication technology"
  - "Cryptocurrency"
  - "History of transportation"
  - "Space colonization"
  - "History of timekeeping"
  - "Space shuttle program"
  - "History of theater"
  - "Ancient Greek philosophy"
  - "Relativity and spacetime"
  - "Nuclear fusion"
  - "Biodiversity conservation"
  - "History of printing press"
  - "Dark web"
  - "Climate change and global warming"
  - "Types of social networks"
  - "History of space exploration"
  - "History of antibiotics"
  - "History of artificial satellites"
  - "Cognitive behavioral therapy"
  - "Exoplanets"
  - "Mars rovers"
  - "Ethics of AI"
  - "Drone technology"
  - "Nuclear energy"
  - "Virtual economies"
  - "Space telescopes"
  - "Submarine communications"
  - "Ecosystems of the Amazon rainforest"
  - "History of ancient China"
  - "Human brain anatomy"
  - "Evolution of reptiles"
  - "Theory of probability"
  - "Exploration of Antarctica"
  - "History of evolution"
  - "Industrial automation"
  - "Augmented reality in medicine"
  - "Artificial photosynthesis"
  - "History of human spaceflight"
  - "Genomics"
  - "Astrophysics"
  - "Space debris and mitigation"
  - "Human cloning ethics"
  - "Brain-computer interfaces"
  - "Quantum entanglement"
  - "Fusion power"
  - "Mars colonization"
  - "Gene therapy"
  - "Artificial neural networks"
  - "Deep learning applications"
  - "Internet of Things (IoT)"
  - "History of telecommunications"
  - "Biotechnology breakthroughs"
  - "History of vaccines"
  - "Autonomous vehicles"
  - "Smart cities"
  - "Solar power innovations"
  - "Sustainable urban planning"
  - "History of electric vehicles"
  - "Carbon capture technology"
  - "Energy storage solutions"
  - "Human genome project"
  - "Theoretical physics"
  - "History of nuclear power"
  - "Tidal energy"
  - "History of the Renaissance"
  - "Genetic algorithms"
  - "Bioinformatics"
  - "Quantum cryptography"
  - "History of space telescopes"
  - "Artificial general intelligence"
  - "Renewable energy technologies"
  - "Self-driving cars"
  - "History of the scientific method"
  - "Digital twins technology"
  - "Quantum supremacy"
  - "DNA sequencing technology"
  - "Molecular biology"
  - "Graphene applications"
  - "Satellite internet technology"
  - "Nanorobotics"
  - "Robotics in space exploration"
  - "Quantum field theory"
  - "History of microbiology"
  - "Synthetic biology"
  - "Augmented reality in education"
  - "History of cryptography"
  - "Space tourism"
  - "Neuroplasticity"
  - "Wearable technology"
  - "Optical computing"
  - "Neuromorphic computing"
  - "Evolution of primates"
  - "Gene editing with CRISPR"
  - "3D bioprinting"
  - "Quantum optics"
  - "Stem cell research"
  - "Nuclear fusion reactors"
  - "Space elevator technology"
  - "Bioengineering"
  - "AI in healthcare"
  - "Astrobiology and life on other planets"
  - "Cognitive neuroscience"
  - "Cyber warfare"
  - "Precision medicine"
  - "Big data in healthcare"
  - "History of semiconductor technology"
  - "Photonic computing"
  - "Brain mapping technology"
  - "Evolution of language"
  - "Quantum sensors"
  - "Memristors"
  - "Cellular agriculture"
  - "Smart agriculture"
  - "Edge computing"
  - "Bioelectricity"
  - "Artificial organs"
  - "Synthetic organisms"
  - "AI in cybersecurity"
  - "Quantum materials"
  - "Virtual tourism"
  - "Blockchain in supply chain"
  - "Superconductivity"
  - "Nanoscale imaging"
  - "Femtotechnology"
  - "Hypersonic flight"
  - "Time dilation"
  - "Space mining"
  - "Asteroid deflection technologies"
  - "Neuroprosthetics"
  - "History of nanotechnology"
  - "Quantum teleportation"
  - "Photonics"
  - "History of paleontology"
  - "Virtual reality in education"
  - "Metaverse technology"
  - "Artificial emotional intelligence"
  - "Neuroethics"
  - "Quantum computing in finance"
  - "Smart grids"
  - "Solar sails"
  - "Advanced robotics"
  - "Renewable ocean energy"
  - "Quantum dots"
  - "Internet censorship"
  - "History of digital art"
  - "Biodegradable plastics"
  - "Humanitarian robotics"
  - "Cryogenics"
  - "The Kardashev scale"
  - "Space-time wormholes"
  - "Mars exploration missions"
  - "AI in environmental monitoring"
  - "Smart homes"
  - "Hydrogen fuel cells"
  - "Artificial photosynthesis for energy"
  - "Electricity generation from algae"
  - "Battery technology breakthroughs"
  - "Electric propulsion in space"
  - "Directed energy weapons"
  - "Carbon nanotubes"
  - "Programmable matter"
  - "Genetic diversity and conservation"
  - "Autonomous drones"
  - "Artificial ecosystems"
  - "Microbiomes"
  - "Cryonics"
  - "Space archaeology"
  - "AI ethics"
  - "Quantum biology"
  - "Multiverse theory"
  - "Terraforming"
  - "Exoskeleton technology"
  - "Holography"
  - "Graphene-based electronics"
  - "Neuroscience of memory"
  - "AI-generated art"
  - "Hyperloop transportation technology"
  - "Self-healing materials"
  - "Waste-to-energy technologies"
  - "Bionic limbs"
  - "Conservation genetics"
  - "In-vitro meat production"
  - "Machine translation"
  - "History of cryptoeconomics"
  - "Global water scarcity"
  - "Remote sensing technologies"
  - "Microgravity research"
  - "Space law"
  - "Swarm robotics"
  - "Quantum radar"
  - "Energy-efficient computing"
  - "Dark energy"
  - "Genetic drift"
  - "Artificial intelligence in space exploration"
  - "Smart textiles"
  - "Neural implants"
  - "Lunar habitats"
  - "Zero-emission vehicles"
  - "Space power generation"
  - "AI in financial markets"
  - "Cyber-physical systems"
  - "Cryptocurrency mining"
  - "AI in natural language processing"
  - "DNA data storage"
  - "Invisibility cloaks"
  - "Mars atmosphere terraforming"
  - "Volcanic eruption prediction"
  - "Biomimetic robotics"
  - "Quantum machine learning"
  - "Molecular nanotechnology"
  - "Solar storm prediction"
  - "Extraterrestrial intelligence"
  - "Neurogenesis"
  - "Cybersecurity and AI integration"
  - "Sustainable fashion technology"
  - "Artificial skin"
  - "Quantum finance"
  - "Space resource utilization"
  - "Ethics of genetic modification"
  - "Human factors engineering"
  - "Organic photovoltaics"
  - "Wireless energy transfer"
  - "3D printed homes"
  - "AI in climate science"
  - "History of space law"
  - "Underwater drones"
  - "AI in robotics"
  - "Quantum error correction"
  - "AI-powered prosthetics"
  - "History of social media"
  - "Internet freedom and privacy"
  - "Advanced prosthetics"
  - "Astrochemistry"
  - "Quantum electrodynamics"
  - "Behavioral genetics"
  - "History of fractals"




# Loop settings to control how many loops of tasks should run
loop_settings:
  min_loops: 5  # Minimum number of loops to run per device
  max_loops: 10 # Maximum number of loops to run per device
